apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-adapter
  namespace: d3os-monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: notification-adapter
  template:
    metadata:
      labels:
        name: notification-adapter
    spec:
      containers:
        - name: notification-adapter
          image: d3osdev/notification-adapter:latest
          command:
            - notification-adapter
            - --ip=socket-server.d3os-monitoring-system
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
          lifecycle:
            preStop:
              httpGet:
                path: /preStop
                port: 8080
                scheme: HTTP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 50Mi
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time

---
apiVersion: v1
kind: Service
metadata:
  name: notification-adapter
  namespace: d3os-monitoring-system
spec:
  selector:
    name: notification-adapter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
