# permissions for end users to view notificationmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationmanager-viewer-role
rules:
- apiGroups:
  - notification.d3os.io
  resources:
  - notificationmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.d3os.io
  resources:
  - notificationmanagers/status
  verbs:
  - get
