# permissions for end users to edit notificationmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationmanager-editor-role
rules:
- apiGroups:
  - notification.d3os.io
  resources:
  - notificationmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.d3os.io
  resources:
  - notificationmanagers/status
  verbs:
  - get
