# value of notification-manager-operator
operator: 
  containers:
    proxy:
      image:
        repo: d3os/kube-rbac-proxy
        tag: v0.8.0
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 5m
          memory: 10Mi
    operator:
      image:
        repo: d3os/notification-manager-operator
        tag: v1.0.0
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 5m
          memory: 20Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


# value of notification-manager
notificationmanager:
  image:
    tag: v1.0.0
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 5m
      memory: 20Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  defaultConfigSelector:
    matchLabels:
      type: default
  receivers:
    tenantKey: user
    globalReceiverSelector:
      matchLabels:
        type: global
    tenantReceiverSelector:
      matchLabels:
        type: tenant
    options:
      dingtalk:
        notificationTimeout: 5
      email:
        notificationTimeout: 5
        deliveryType: bulk
      global:
        templateFile:
          - /etc/notification-manager/template
      slack:
        notificationTimeout: 5
      webhook:
        notificationTimeout: 5
      wechat:
        notificationTimeout: 5
  notificationManagerNamespaces:
    - d3os-monitoring-system
  volumeMounts:
    - mountPath: /etc/notification-manager/
      name: notification-manager-template
  volumes:
    - configMap:
        defaultMode: 420
        name: notification-manager-template
      name: notification-manager-template
